Add health check

diff --git a/.github/workflows/backend-ci.yml b/.github/workflows/backend-ci.yml
--- a/.github/workflows/backend-ci.yml
+++ b/.github/workflows/backend-ci.yml
@@ -171,3 +171,52 @@ jobs:
         uses: jwgmeligmeyling/checkstyle-github-action@master
         with:
           path: ${{env.WORKING_DIRECTORY}}/target/checkstyle-result.xml
+
+
+  si-3-containerize:
+    runs-on: ubuntu-latest
+    needs: ["sd-1-build"]
+
+    defaults:
+      run:
+        working-directory: backend
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Log Working Directory as Environment Variable
+        run: |
+          echo "WORKING_DIRECTORY=$(pwd)" >> $GITHUB_ENV
+
+      - name: Download built artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: sprawler-backend-artifact
+          path: ${{env.WORKING_DIRECTORY}}/target
+
+      - name: Build Docker image
+        run: |
+          docker build -t sprawler-backend:latest ${{env.WORKING_DIRECTORY}}
+
+      - name: Run Docker container
+        run: |
+          docker run -d --name sprawler-backend -p 8080:8080 sprawler-backend:latest
+
+      - name: Wait for 5 seconds
+        run: sleep 5
+
+      - name: Check Docker container status
+        run: |
+          if [ "$(docker inspect -f '{{.State.Running}}' sprawler-backend)" != "true" ]; then
+          echo "Container is not running"
+          exit 1
+          fi
+
+      - name: Check health of Docker container
+        run: |
+          sleep 10 # Wait for the container to initialize
+          if ! curl --fail http://localhost:8080/health; then
+            echo "Health check failed"
+            exit 1
+          fi 
